site_name: airball
repo_url: https://github.com/zyrxvo/airball
repo_name: zyrxvo/airball
edit_uri: ""
nav:
  - 'home': index.md
  - 'examples': 
    - 'overview': example.md
    - 'basics': examples/Basics.ipynb
    - 'imf': examples/IMF.ipynb
    - 'stellar-environments': examples/Stellar_Environments.ipynb
    - 'adiabatic-tests': examples/Adiabatic.ipynb

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - wikilinks
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mas.to/@zyrxvo
    - icon: fontawesome/brands/github
      link: https://github.com/zyrxvo/airball

plugins:
  - search
  - mkdocs-jupyter
