site_name: AIRBALL
repo_url: https://github.com/zyrxvo/airball
repo_name: zyrxvo/airball
edit_uri: ""
nav:
  - 'Home': index.md
  - 'API':
    - 'Overview': api/index.md
    - 'Core': api/core.md
    - 'Stars': api/stars.md
    - 'Environments': api/environments.md
    - 'Initial Mass Function (IMF)': api/imf.md
    - 'Analytic Estimates': api/analytic.md
    - 'Tools': api/tools.md
    - 'Units': api/units.md
  - 'Examples': 
    - 'Overview': examples/index.md
    - 'Getting Started': examples/getting-started.ipynb
    - 'Basics': examples/basics.ipynb
    - 'IMF': examples/imf.ipynb
    - 'Stellar Environments': examples/stellar-environments.ipynb
    - 'Multiple Flybys': examples/multiple-flybys.ipynb
    - 'Adiabatic Tests': examples/adiabatic-tests.ipynb

theme:
  name: material
  logo: img/airball-white.png
  favicon: img/favicon.ico
  features:
    - navigation.tabs
    - toc.integrate
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.arithmatex
  - wikilinks
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js      
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mas.to/@zyrxvo
    - icon: fontawesome/brands/github
      link: https://github.com/zyrxvo/airball

plugins:
  - search
  - mkdocs-jupyter
  - exclude:
      glob:
        - docs/examples/.ipynb_checkpoints/*
        - docs/examples/examples_data/*
        - "*.c"
        - "*.h"
        - "*.o"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_root_heading: true
            heading_level: 4
            show_source: true
