name: Pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@v9.0.0
      with:
        version: "0.12.5"
        python-version: "3.14"

    - name: Run pre-commit
      run: uv run --frozen --only-dev pre-commit run --all-files
